/**************************************************************************************
 * Original Author : Anthony Leatherwood (adleatherwood@gmail.com)
 * Source Location : https://github.com/Fastlite/DrivenDb
 *
 * This source is subject to the Microsoft Public License.
 * Link: http://www.microsoft.com/en-us/openness/licenses.aspx
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 **************************************************************************************/

using System.Text;

namespace DrivenDbConsole.Generator
{
   internal class FileWriter
   {
      private readonly StringBuilder _output = new StringBuilder();

      public string WriteHeader(string @namespace)
      {
         WriteLine("/* Generated by the DrivenDb Entity Generator. Do not modify. */");
         WriteLine("");
         WriteLine("using System;");
         WriteLine("using System.ComponentModel;");
         //WriteLine("using System.Data.Linq.Mapping;");
         WriteLine("using System.Runtime.Serialization;");
         WriteLine("using DrivenDb;");
         WriteLine("");
         WriteLine("namespace " + @namespace);
         WriteLine("{");

         return _output.ToString();
      }

      public string WriteFooter()
      {
         return "}";
      }

      private void WriteLine(string text)
      {
         _output.AppendLine(text);
      }
   }
}
